# LanguageRooms app image — multi-stage, standalone Next.js output.
#
# Build:  docker build -t languagerooms .
#         (pass --build-arg NEXT_PUBLIC_LIVEKIT_URL=wss://sfu.example.com for
#          production — NEXT_PUBLIC_* values are inlined at build time)
# Run:    see docker-compose.yml (`--profile full`) or docs/deployment.md

# ── deps ─────────────────────────────────────────────────────────────────────
FROM node:22-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
COPY prisma ./prisma
RUN npm ci

# ── build ────────────────────────────────────────────────────────────────────
FROM node:22-alpine AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_LIVEKIT_URL=ws://localhost:7890
ENV NEXT_PUBLIC_LIVEKIT_URL=$NEXT_PUBLIC_LIVEKIT_URL

# Prisma client is generated by @prisma/client postinstall, but be explicit.
RUN npx prisma generate
# Dummy values so lib/env.ts validation passes during static generation;
# real values come from the runtime environment.
RUN DATABASE_URL="postgresql://build:build@localhost:5432/build" \
    SESSION_SECRET="build-time-placeholder-secret-0123456789abcdef" \
    LIVEKIT_API_KEY="build" \
    LIVEKIT_API_SECRET="build-time-placeholder" \
    LIVEKIT_HOST="http://localhost:7890" \
    npm run build

# ── runner ───────────────────────────────────────────────────────────────────
FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
# Prisma CLI for `migrate deploy` at container start.
RUN npm install --global prisma@6.19.3

# Non-root user; writable dirs for dev-mode evidence/upload stores.
RUN addgroup -S app && adduser -S app -G app \
    && mkdir -p /data/evidence /data/uploads \
    && chown -R app:app /data

COPY --from=build --chown=app:app /app/.next/standalone ./
COPY --from=build --chown=app:app /app/.next/static ./.next/static
COPY --from=build --chown=app:app /app/public ./public
COPY --from=build --chown=app:app /app/prisma ./prisma

USER app
EXPOSE 3000
ENV PORT=3000 HOSTNAME=0.0.0.0 \
    EVIDENCE_STORAGE_DIR=/data/evidence \
    UPLOAD_STORAGE_DIR=/data/uploads

# Apply pending migrations, then start the standalone server.
CMD ["sh", "-c", "prisma migrate deploy && node server.js"]
